export const ActionTypes = {
    CART_ADD: "CART_ADD",
    CART_REMOVE: "CART_REMOVE",
    CHECKOUT_REQUEST: "CHECKOUT_REQUEST",
    CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
    CHECKOUT_ERROR: "CHECKOUT_ERROR",


}