export const ActionTypes = {

    FETCH_DASHBOARDS_REQUEST: "FETCH_DASHBOARDS_REQUEST_1",
    FETCH_DASHBOARDS_SUCCESS: "FETCH_DASHBOARDS_SUCCESS_1",
    FETCH_DASHBOARDS_ERROR: "FETCH_DASHBOARDS_ERROR_1",

}